name:                queryClinVar
version:             0.1.0.0
github:              "achilleasNP/queryClinVar"
license:             BSD3
author:              "Achilleas Pitsillides"
maintainer:          "example@example.com"
copyright:           "2022 Achilleas Pitsillides"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/achilleasNP/queryClinVar#readme>

dependencies:
- base >= 4.7 && < 5
- req >= 3 && <4
- aeson >= 2 && <3
- unordered-containers >= 0.2 && < 1
- text >= 1 && < 2
- vector >= 0.12 && < 1
- process >= 1 && < 2
- directory >= 1.3 && < 2
- optparse-applicative >= 0.16 && < 1
- portable-lines >= 0.1 && < 1

library:
  source-dirs: src

executables:
  queryClinVar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queryClinVar

tests:
  queryClinVar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - queryClinVar
